apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-service
  namespace: github
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "4886"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-service
  template:
    metadata:
      labels:
        app: github-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "4886"
    spec:
      containers:
        - name: github-service
          image: kanghyeonseung/github-service
          ports:
            - containerPort: 4886
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-volume
          secret:
            secretName: github-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: github-service
  namespace: github
spec:
  selector:
    app: github-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4886
  type: ClusterIP